export const EQUIPMENT_TRANSLATIONS = {
  en: { filter: 'Filter', filter_power: 'Filter power', heating: 'Heating', heating_power: 'Heating power', on: 'On', off: 'Off' },
  de: { filter: 'Filter', filter_power: 'Filterleistung', heating: 'Heizung', heating_power: 'Heizleistung', on: 'Ein', off: 'Aus' },
  fr: { filter: 'Filtration', filter_power: 'Puissance du filtre', heating: 'Chauffage', heating_power: 'Puissance du chauffage', on: 'Marche', off: 'Arrêt' },
  it: { filter: 'Filtro', filter_power: 'Potenza del filtro', heating: 'Riscaldamento', heating_power: 'Potenza del riscaldamento', on: 'Acceso', off: 'Spento' },
  es: { filter: 'Filtración', filter_power: 'Potencia del filtro', heating: 'Calefacción', heating_power: 'Potencia de calefacción', on: 'Encendido', off: 'Apagado' },
};
export const CONTEXT_TRANSLATIONS = {
  en: { ambient_temperature: 'Ambient temperature', balance_profile: 'Water balance profile', water_air_delta: 'Water − air' },
  de: { ambient_temperature: 'Umgebungstemperatur', balance_profile: 'Wasserbalance-Profil', water_air_delta: 'Wasser − Luft' },
  fr: { ambient_temperature: 'Température ambiante', balance_profile: 'Profil d’équilibre de l’eau', water_air_delta: 'Eau − air' },
  it: { ambient_temperature: 'Temperatura ambiente', balance_profile: 'Profilo di equilibrio dell’acqua', water_air_delta: 'Acqua − aria' },
  es: { ambient_temperature: 'Temperatura ambiente', balance_profile: 'Perfil de equilibrio del agua', water_air_delta: 'Agua − aire' },
};
export const TRANSLATIONS = {
  en: {
    card_title: 'Pool Water Quality', language: 'Language', title: 'Title', ph: 'pH', free_chlorine: 'Free chlorine', orp: 'ORP', temperature: 'Temperature', salinity: 'Salinity', tds: 'TDS', ec: 'EC', target: 'Target', recommendation: 'Recommended next step', unknown: '{label}: no valid reading or target configured', below: '{label}: below target ({range})', above: '{label}: above target ({range})', within: '{label}: within target ({range})', grade_missing: 'configure pH and free chlorine to calculate a grade', grade_waiting: 'waiting for valid pH and free-chlorine readings', grade_chlorine_low: 'free chlorine is below its configured minimum', grade_critical: '{label} is outside its critical range', grade_multiple: 'multiple primary readings need attention', grade_one: 'one primary reading needs attention', grade_support: 'primary readings are on target; a supporting reading needs attention', grade_all: 'all configured readings with targets are on target', ph_low: 'pH is low. Confirm with a drop test, then use a pool-specific pH increaser according to its label. Retest before making another adjustment.', ph_high: 'pH is high. Confirm with a drop test, then use a pool-specific pH reducer according to its label. Retest before making another adjustment.', chlorine_low: 'Free chlorine is low. Confirm with a DPD test, then raise it with your chlorinator or a labelled chlorine product. Circulate and retest.', chlorine_high: 'Free chlorine is high. Pause chlorination and retest before swimming; follow the chemical label and local guidance.', orp_low: 'ORP is low. Verify pH and free chlorine with a reliable test and correct those values rather than dosing from ORP alone.', orp_high: 'ORP is high. Verify free chlorine and pH with a reliable test before changing chlorinator settings.', temperature_low: 'Temperature is below the configured comfort target. Adjust heating if your pool has it.', temperature_high: 'Temperature is above the configured comfort target. Reduce heating or adjust cover use as appropriate.', salinity_low: 'Salinity is below your configured target. Follow your salt chlorinator manufacturer’s instructions before adding salt.', salinity_high: 'Salinity is above your configured target. Follow your chlorinator manufacturer’s instructions; dilution may be required.', tds: 'TDS', tds_low: 'TDS is outside your configured target. Use it as a trend indicator and confirm overall balance with a proper water test.', tds_high: 'TDS is outside your configured target. Use it as a trend indicator and confirm overall balance with a proper water test.', ec_low: 'EC is outside your configured target. Check probe calibration and use a proper water test before adjusting chemicals.', ec_high: 'EC is outside your configured target. Check probe calibration and use a proper water test before adjusting chemicals.', also_ph: ' Also correct pH after confirming both readings.',
  },
  de: {
    card_title: 'Poolwasserqualität', language: 'Sprache', title: 'Titel', ph: 'pH', free_chlorine: 'Freies Chlor', orp: 'Redox', temperature: 'Temperatur', salinity: 'Salzgehalt', tds: 'TDS', ec: 'Leitfähigkeit', target: 'Zielbereich', recommendation: 'Empfohlener nächster Schritt', unknown: '{label}: kein gültiger Messwert oder Zielbereich', below: '{label}: unter Zielbereich ({range})', above: '{label}: über Zielbereich ({range})', within: '{label}: im Zielbereich ({range})', grade_missing: 'pH und freies Chlor für eine Bewertung konfigurieren', grade_waiting: 'warte auf gültige pH- und Chlorwerte', grade_chlorine_low: 'freies Chlor liegt unter dem konfigurierten Minimum', grade_critical: '{label} liegt außerhalb des kritischen Bereichs', grade_multiple: 'mehrere Primärwerte benötigen Aufmerksamkeit', grade_one: 'ein Primärwert benötigt Aufmerksamkeit', grade_support: 'Primärwerte sind im Zielbereich; ein unterstützender Wert benötigt Aufmerksamkeit', grade_all: 'alle konfigurierten Werte mit Zielbereich sind im Zielbereich', ph_low: 'pH ist zu niedrig. Mit einem Tropftest bestätigen und anschließend einen geeigneten pH-Heber gemäß Etikett verwenden. Danach erneut messen.', ph_high: 'pH ist zu hoch. Mit einem Tropftest bestätigen und anschließend einen geeigneten pH-Senker gemäß Etikett verwenden. Danach erneut messen.', chlorine_low: 'Freies Chlor ist zu niedrig. Mit einem DPD-Test bestätigen und über die Salzelektrolyse oder ein zugelassenes Chlorprodukt anheben. Umwälzen und erneut messen.', chlorine_high: 'Freies Chlor ist zu hoch. Chlorung pausieren und vor dem Baden erneut messen; Produktetikett und örtliche Vorgaben beachten.', orp_low: 'Redox ist niedrig. pH und freies Chlor zuverlässig prüfen und diese Werte korrigieren, nicht allein nach Redox dosieren.', orp_high: 'Redox ist hoch. Freies Chlor und pH zuverlässig prüfen, bevor die Chlorung verändert wird.', temperature_low: 'Temperatur liegt unter dem Komfortziel. Falls vorhanden, Heizung anpassen.', temperature_high: 'Temperatur liegt über dem Komfortziel. Heizung oder Abdeckung entsprechend anpassen.', salinity_low: 'Salzgehalt liegt unter dem Zielbereich. Vor Zugabe von Salz die Anleitung des Salzchlorinators beachten.', salinity_high: 'Salzgehalt liegt über dem Zielbereich. Anleitung des Salzchlorinators beachten; Verdünnung kann erforderlich sein.', tds_low: 'TDS liegt außerhalb des Zielbereichs. Als Trendwert verwenden und die Wasserbalance mit einem geeigneten Test prüfen.', tds_high: 'TDS liegt außerhalb des Zielbereichs. Als Trendwert verwenden und die Wasserbalance mit einem geeigneten Test prüfen.', ec_low: 'Leitfähigkeit liegt außerhalb des Zielbereichs. Sondenkalibrierung prüfen und vor einer Chemikalienzugabe einen Wassertest durchführen.', ec_high: 'Leitfähigkeit liegt außerhalb des Zielbereichs. Sondenkalibrierung prüfen und vor einer Chemikalienzugabe einen Wassertest durchführen.', also_ph: ' pH nach Bestätigung beider Werte ebenfalls korrigieren.',
  },
  fr: {
    card_title: 'Qualité de l’eau de piscine', language: 'Langue', title: 'Titre', ph: 'pH', free_chlorine: 'Chlore libre', orp: 'ORP', temperature: 'Température', salinity: 'Salinité', tds: 'TDS', ec: 'Conductivité', target: 'Plage cible', recommendation: 'Prochaine étape recommandée', unknown: '{label} : mesure ou plage cible non valide', below: '{label} : sous la cible ({range})', above: '{label} : au-dessus de la cible ({range})', within: '{label} : dans la cible ({range})', grade_missing: 'configurez le pH et le chlore libre pour calculer une note', grade_waiting: 'en attente de mesures valides de pH et de chlore libre', grade_chlorine_low: 'le chlore libre est sous le minimum configuré', grade_critical: '{label} est hors de sa plage critique', grade_multiple: 'plusieurs mesures principales demandent attention', grade_one: 'une mesure principale demande attention', grade_support: 'les mesures principales sont bonnes ; une mesure secondaire demande attention', grade_all: 'toutes les mesures configurées avec une cible sont bonnes', ph_low: 'Le pH est bas. Confirmez avec un test goutte-à-goutte, puis utilisez un rehausseur de pH adapté selon son étiquette. Testez à nouveau.', ph_high: 'Le pH est élevé. Confirmez avec un test goutte-à-goutte, puis utilisez un réducteur de pH adapté selon son étiquette. Testez à nouveau.', chlorine_low: 'Le chlore libre est bas. Confirmez avec un test DPD, puis augmentez-le avec votre chlorinateur ou un produit chloré adapté. Faites circuler et testez à nouveau.', chlorine_high: 'Le chlore libre est élevé. Suspendez la chloration et testez à nouveau avant la baignade ; suivez l’étiquette et les règles locales.', orp_low: 'L’ORP est bas. Vérifiez pH et chlore libre avec un test fiable ; ne dosez pas à partir de l’ORP seul.', orp_high: 'L’ORP est élevé. Vérifiez pH et chlore libre avant de modifier la chloration.', temperature_low: 'La température est sous le confort configuré. Ajustez le chauffage si disponible.', temperature_high: 'La température est au-dessus du confort configuré. Ajustez le chauffage ou la couverture.', salinity_low: 'La salinité est sous la cible. Suivez le manuel du chlorinateur avant d’ajouter du sel.', salinity_high: 'La salinité est au-dessus de la cible. Suivez le manuel du chlorinateur ; une dilution peut être nécessaire.', tds_low: 'Les TDS sont hors cible. Utilisez-les comme tendance et confirmez l’équilibre avec un test adapté.', tds_high: 'Les TDS sont hors cible. Utilisez-les comme tendance et confirmez l’équilibre avec un test adapté.', ec_low: 'La conductivité est hors cible. Vérifiez l’étalonnage de la sonde et testez l’eau avant un ajustement.', ec_high: 'La conductivité est hors cible. Vérifiez l’étalonnage de la sonde et testez l’eau avant un ajustement.', also_ph: ' Corrigez aussi le pH après confirmation des deux mesures.',
  },
  it: {
    card_title: 'Qualità dell’acqua della piscina', language: 'Lingua', title: 'Titolo', ph: 'pH', free_chlorine: 'Cloro libero', orp: 'ORP', temperature: 'Temperatura', salinity: 'Salinità', tds: 'TDS', ec: 'Conducibilità', target: 'Intervallo obiettivo', recommendation: 'Prossimo passo consigliato', unknown: '{label}: nessuna misura valida o intervallo configurato', below: '{label}: sotto l’obiettivo ({range})', above: '{label}: sopra l’obiettivo ({range})', within: '{label}: nell’obiettivo ({range})', grade_missing: 'configura pH e cloro libero per calcolare il giudizio', grade_waiting: 'in attesa di letture valide di pH e cloro libero', grade_chlorine_low: 'il cloro libero è sotto il minimo configurato', grade_critical: '{label} è fuori dall’intervallo critico', grade_multiple: 'più letture principali richiedono attenzione', grade_one: 'una lettura principale richiede attenzione', grade_support: 'le letture principali sono nell’obiettivo; una lettura di supporto richiede attenzione', grade_all: 'tutte le letture configurate con obiettivo sono nell’obiettivo', ph_low: 'Il pH è basso. Conferma con un test a gocce, poi usa un aumentatore di pH adatto secondo l’etichetta. Riesegui il test.', ph_high: 'Il pH è alto. Conferma con un test a gocce, poi usa un riduttore di pH adatto secondo l’etichetta. Riesegui il test.', chlorine_low: 'Il cloro libero è basso. Conferma con un test DPD, poi aumentalo con il clorinatore o un prodotto al cloro idoneo. Fai circolare e riesegui il test.', chlorine_high: 'Il cloro libero è alto. Sospendi la clorazione e riesegui il test prima di nuotare; segui etichetta e regole locali.', orp_low: 'L’ORP è basso. Verifica pH e cloro libero con un test affidabile; non dosare in base al solo ORP.', orp_high: 'L’ORP è alto. Verifica pH e cloro libero prima di modificare la clorazione.', temperature_low: 'La temperatura è sotto il comfort configurato. Regola il riscaldamento se disponibile.', temperature_high: 'La temperatura è sopra il comfort configurato. Regola riscaldamento o copertura.', salinity_low: 'La salinità è sotto l’obiettivo. Segui il manuale del clorinatore prima di aggiungere sale.', salinity_high: 'La salinità è sopra l’obiettivo. Segui il manuale del clorinatore; potrebbe servire diluire.', tds_low: 'I TDS sono fuori obiettivo. Usali come tendenza e conferma l’equilibrio con un test adeguato.', tds_high: 'I TDS sono fuori obiettivo. Usali come tendenza e conferma l’equilibrio con un test adeguato.', ec_low: 'La conducibilità è fuori obiettivo. Verifica la calibrazione della sonda prima di correggere i prodotti.', ec_high: 'La conducibilità è fuori obiettivo. Verifica la calibrazione della sonda prima di correggere i prodotti.', also_ph: ' Correggi anche il pH dopo aver confermato entrambe le letture.',
  },
  es: {
    card_title: 'Calidad del agua de la piscina', language: 'Idioma', title: 'Título', ph: 'pH', free_chlorine: 'Cloro libre', orp: 'ORP', temperature: 'Temperatura', salinity: 'Salinidad', tds: 'TDS', ec: 'Conductividad', target: 'Rango objetivo', recommendation: 'Siguiente paso recomendado', unknown: '{label}: no hay lectura válida ni rango configurado', below: '{label}: por debajo del objetivo ({range})', above: '{label}: por encima del objetivo ({range})', within: '{label}: dentro del objetivo ({range})', grade_missing: 'configure pH y cloro libre para calcular la calificación', grade_waiting: 'esperando lecturas válidas de pH y cloro libre', grade_chlorine_low: 'el cloro libre está por debajo del mínimo configurado', grade_critical: '{label} está fuera del rango crítico', grade_multiple: 'varias lecturas principales requieren atención', grade_one: 'una lectura principal requiere atención', grade_support: 'las lecturas principales están bien; una lectura secundaria requiere atención', grade_all: 'todas las lecturas configuradas con objetivo están bien', ph_low: 'El pH es bajo. Confírmelo con una prueba de gotas y use un elevador de pH según su etiqueta. Vuelva a medir.', ph_high: 'El pH es alto. Confírmelo con una prueba de gotas y use un reductor de pH según su etiqueta. Vuelva a medir.', chlorine_low: 'El cloro libre es bajo. Confírmelo con una prueba DPD y súbalo con el clorador o un producto de cloro adecuado. Recircule y vuelva a medir.', chlorine_high: 'El cloro libre es alto. Pause la cloración y vuelva a medir antes de nadar; siga la etiqueta y las normas locales.', orp_low: 'El ORP es bajo. Compruebe pH y cloro libre con una prueba fiable; no dosifique solo según el ORP.', orp_high: 'El ORP es alto. Compruebe pH y cloro libre antes de cambiar la cloración.', temperature_low: 'La temperatura está por debajo del confort configurado. Ajuste la calefacción si está disponible.', temperature_high: 'La temperatura está por encima del confort configurado. Ajuste la calefacción o la cubierta.', salinity_low: 'La salinidad está por debajo del objetivo. Siga el manual del clorador antes de añadir sal.', salinity_high: 'La salinidad está por encima del objetivo. Siga el manual del clorador; puede requerirse dilución.', tds_low: 'Los TDS están fuera del objetivo. Úselos como tendencia y confirme el equilibrio con una prueba adecuada.', tds_high: 'Los TDS están fuera del objetivo. Úselos como tendencia y confirme el equilibrio con una prueba adecuada.', ec_low: 'La conductividad está fuera del objetivo. Compruebe la calibración de la sonda antes de ajustar productos.', ec_high: 'La conductividad está fuera del objetivo. Compruebe la calibración de la sonda antes de ajustar productos.', also_ph: ' Corrija también el pH tras confirmar ambas lecturas.',
  },
};

export const LANGUAGE_OPTIONS = [
  ['en', 'English'], ['de', 'Deutsch'], ['fr', 'Français'], ['it', 'Italiano'], ['es', 'Español'],
].map(([value, label]) => ({ value, label }));

export const translate = (language, key, values = {}) => {
  const text = TRANSLATIONS[language]?.[key]
    || EQUIPMENT_TRANSLATIONS[language]?.[key]
    || CONTEXT_TRANSLATIONS[language]?.[key]
    || TRANSLATIONS.en[key]
    || EQUIPMENT_TRANSLATIONS.en[key]
    || CONTEXT_TRANSLATIONS.en[key]
    || key;
  return text.replace(/\{(\w+)\}/g, (_, name) => values[name] ?? `{${name}}`);
};
